---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: argocd-admin-mq
  namespace: ap-run
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops

---

apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-autopilot-operator
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  displayName: IBM Autopilot Operator
  image: us.icr.io/abp-builds/ibm-autopilot-operator-catalog:latest-amd64
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: autopilot-operator
  namespace: ap-run
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: autopilot-operator
  source: ibm-autopilot-operator
  sourceNamespace: openshift-marketplace
